- name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: NIHAL-JAGDALE
          output_path: trophy.svg
          theme: darkhub
          rank: "-?"
          token: ${{ secrets.GITHUB_TOKEN }}
